apiVersion: v1
kind: ConfigMap
metadata:
  name: drive-unity-config
  namespace: drive-unity
  labels:
    app.kubernetes.io/name: drive-unity-app
    app.kubernetes.io/part-of: drive-unity
data:
  NEXT_PUBLIC_APP_URL: "https://driveunity.example.com"
  NEXT_PUBLIC_BASE_URL: "https://driveunity.example.com"
  NODE_ENV: "production"
