apiVersion: v1
kind: Secret
metadata:
  name: drive-unity-secret
  namespace: drive-unity
  labels:
    app.kubernetes.io/name: drive-unity-app
    app.kubernetes.io/part-of: drive-unity
type: Opaque
# Replace base64 values before applying:
#   echo -n 'your-value' | base64
data:
  # postgresql://driveunity:changemeplease@postgres.drive-unity.svc.cluster.local:5432/driveunity
  DATABASE_URL: cG9zdGdyZXNxbDovL2RyaXZldW5pdHk6Y2hhbmdlbWVwbGVhc2VAcG9zdGdyZXMuZHJpdmUtdW5pdHkuc3ZjLmNsdXN0ZXIubG9jYWw6NTQzMi9kcml2ZXVuaXR5
